spring.application.name=Ostad Mart

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/ostadmart
spring.datasource.username=root
spring.datasource.password=hiQwLs8YSgayQoSg62kHNxMxy4ggxubT
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# JWT (15 Minutes)
app.jwt.secret=${JWT_SECRET:BQIzGOqxfS6xNQgLYKbU16U7Th3NWtNigAsVfZWJAFs=}
app.jwt.expiration=${JWT_EXPIRATION:9000000}

# SSL Commerz
ssl_commerz.sandbox.url=https://sandbox.sslcommerz.com/gwprocess/v4/api.php
ssl_commerz.sandbox.store_id=ostad69b9ca619bb66
ssl_commerz.sandbox.store_passwd=ostad69b9ca619bb66@ssl
payment.url.on_success=http://localhost:8080/success
payment.url.on_failure=http://localhost:8080/fail
payment.url.on_cancel=http://localhost:8080/cancel
payment.url.ipn=http://localhost:8080/api/payment/ipn
